### ISSUE TITLE
if можно убрать, написав его в SQL запросе

### ISSUE THREAD

**Issue by DmitriyRudenskiy** [urashav/LoftSchool_VP_2#4]
$user = self::$dbh->query("SELECT * FROM users WHERE id='" . $data['id'] . "'");
        $user->setFetchMode(PDO::FETCH_ASSOC);
        $userData = $user->fetch();
        if ($data['password'] == $userData['password']) {
            return $userData;
        }
        return false;

**Comment by urashav** [comment]
Проверка бессмысленна, убрал вообще.
